// <auto-generated />
using FristExersiceZhenic.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FristExersiceZhenic.Migrations
{
    [DbContext(typeof(MyZhenicDbContext))]
    partial class MyZhenicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FristExersiceZhenic.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Category = "اپل",
                            Description = "13 عالیه ولی گرونه ",
                            Name = "آیفون 13",
                            Price = 80
                        },
                        new
                        {
                            id = 2,
                            Category = "اپل",
                            Description = "عالیه ولی گرونه 14 ",
                            Name = "آیفون 14",
                            Price = 90
                        },
                        new
                        {
                            id = 3,
                            Category = "اپل",
                            Description = "عالیه ولی گرونه 15 ",
                            Name = "آیفون 15",
                            Price = 100
                        },
                        new
                        {
                            id = 4,
                            Category = "سامسونگ",
                            Description = "ارزونه ولی عالی نیست ",
                            Name = "گلکسی a56",
                            Price = 38
                        },
                        new
                        {
                            id = 5,
                            Category = "سامسونگ",
                            Description = "عالیه گرونم نیست ",
                            Name = "گلکسی s24 fe",
                            Price = 48
                        },
                        new
                        {
                            id = 6,
                            Category = "سامسونگه",
                            Description = "عالیه ولی گرونه خیلیم گرونه ",
                            Name = "گلکسی s25 اولترا",
                            Price = 150
                        },
                        new
                        {
                            id = 7,
                            Category = "شیائومی",
                            Description = "ادای عالی هارو در میاره... نه ارزونه  نه گرون  ",
                            Name = "شیائومی 15 الترا",
                            Price = 70
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
